kholeisi2/routes/web.php
<?php

use App\Http\Controllers\BilletsController;
use App\Http\Controllers\CommentairesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('billets',BilletsController::class);

kholeisi2/app/Models/Billets.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Billets extends Model
{
    use HasFactory;
}

kholeisi2/app/Models/Commentaires.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Commentaires extends Model
{
    use HasFactory;
}

kholeisi2/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

kholeisi2/app/Http/Controllers/BilletsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreBilletsRequest;
use App\Http\Requests\UpdateBilletsRequest;
use App\Models\Billets;

class BilletsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $billets = Billets::all();
        return view('billets',compact('billets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreBilletsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBilletsRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Billets  $billets
     * @return \Illuminate\Http\Response
     */
    public function show(Billets $billets)
    {
        //
        $commentaires = $billets->commentaires;
        return view('commentaires',compact('billets','commentaires'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Billets  $billets
     * @return \Illuminate\Http\Response
     */
    public function edit(Billets $billets)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateBilletsRequest  $request
     * @param  \App\Models\Billets  $billets
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBilletsRequest $request, Billets $billets)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Billets  $billets
     * @return \Illuminate\Http\Response
     */
    public function destroy(Billets $billets)
    {
        //
    }
}

kholeisi2/app/Http/Controllers/CommentairesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCommentairesRequest;
use App\Http\Requests\UpdateCommentairesRequest;
use App\Models\Commentaires;


class CommentairesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCommentairesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCommentairesRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Commentaires  $commentaires
     * @return \Illuminate\Http\Response
     */
    public function show(Commentaires $commentaires)
    {
        //  
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Commentaires  $commentaires
     * @return \Illuminate\Http\Response
     */
    public function edit(Commentaires $commentaires)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCommentairesRequest  $request
     * @param  \App\Models\Commentaires  $commentaires
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCommentairesRequest $request, Commentaires $commentaires)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Commentaires  $commentaires
     * @return \Illuminate\Http\Response
     */
    public function destroy(Commentaires $commentaires)
    {
        //
    }
}

kholeisi2/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

kholeisi2/resources/views/billets.blade.php
@extends('layouts.layout')

@section('titrePage')
    Les billets
@endsection


@section('contenu')
<body>
@foreach($billets as $b)
    <a href="{{ route('billets.show', $b->id) }}"><h2>{{ $b->BIL_Titre }}</h2></a>
    <a>{{ $b->BIL_Date}}</a><br>
    <a>{{ $b->BIL_Contenu}}</a><br>
    <br>
@endforeach
</body>
@endsection

kholeisi2/resources/views/commentaires.blade.php
@extends('layouts.layout')

@section('titrePage')
    Commentaires
@endsection

@section('contenu')
    <div class="card">
        <header class="card-header">
            <h5 class="card-header-title">Titre: {{ $billets->BIL_Titre }}</h5>
        </header>
        <div class="card-content">
            <div class="content">
                <a>{{ $billets->BIL_Date}}</a><br>
                <a>{{ $billets->BIL_Contenu}}</a><br>
            </div>
        </div>
    </div>
@endsection

kholeisi2/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="css/style.css">

        <title>
            @yield('titrePage')
        </title>
    </head>
    <body>
        <header>
            <h1>Tous les billets :</h1>
        </header>
        @yield('contenu')
        <br>
        <footer class="footer">
            MangaWeb - copyright 3AInfo - 2022
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>